### ISSUE TITLE
Reason for not using xref for elisp

### ISSUE THREAD

**Issue by valignatev** [jojojames/smart-jump#14]
Hi, thanks for the package! I'm looking into employing it for my workflow.
I've noticed that you're trying to use slime for elisp navigation. Is there a reason it's preferred over xref-find-definition/references? I think those two are doing a great job and they're built in, but maybe I don't know something. 

P.S. Now I should either setup my own register for elisp with xref, or install slime (and I don't want to).

**Comment by valignatev** [comment]
For the reference, my register:
```elisp
(smart-jump-register :modes 'emacs-lisp-mode
                     :jump-fn 'xref-find-definitions
                     :refs-fn 'xref-find-references
                     :pop-fn 'pop-tag-mark
                     :should-jump t
                     :heuristic 'error)
```

**Comment by jojojames** [comment]
It's because I use it. :)

I think we can set up emacs lisp mode with xref too in front of dumb-jump.

My list looks like this right now:

```
smart-jump-list is a variable defined in ‘smart-jump.el’.
Its value is
((:jump-fn lispy-goto-symbol :pop-fn pop-tag-mark :refs-fn smart-jump-simple-find-references :before-jump-fn nil :should-jump t :heuristic error :refs-heuristic error :async nil :order 0)
 (:jump-fn elisp-slime-nav-find-elisp-thing-at-point :pop-fn pop-tag-mark :refs-fn xref-find-references :before-jump-fn nil :should-jump smart-jump-elisp-slime-nav-available-p :heuristic error :refs-heuristic error :async nil :order 1)
 (:jump-fn dumb-jump-go :pop-fn dumb-jump-back :refs-fn smart-jump-simple-find-references :should-jump t :heuristic point :async nil :order 1000))
```

So it uses lispy -> elisp-slime-nav- > dumb-jump.

I think elisp-slime-nav uses xref under the hood so I'd be ok with a PR to add xref for elisp (with precedence after elisp-slime-nav).

End result can be lispy -> elisp-slime-nav -> xref -> dumb-jump.

PR would be great, otherwise once time frees up, I'll look into it.

**Comment by jojojames** [comment]
Added.
